name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Lint
      run: npm run lint
      
    - name: Run Tests
      run: npm run test:coverage
      
    - name: Jest coverage report
      if: github.event_name == 'pull_request'
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: ./coverage/coverage-summary.json
        title: Code Coverage Report
        summary-title: Coverage Summary
        badge-title: Coverage Badge

    - name: Update README with coverage badges
      if: github.ref == 'refs/heads/main-test'
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: ./coverage/coverage-summary.json
        badge-actions-enabled: true
        update-readme-with-badge: true
